- name: BCM Ansible module Demo
  hosts: bcm
  gather_facts: false
  collections:
    - brightcomputing.bcm100
  tasks:
    - name: create login node category
      category:
        name: "{{ catname }}"
        cloneFrom: default
        state: present
    - name: Assigning software image to login node category
      category:
        name: "{{ catname }}"
        softwareImageProxy:
           parentSoftwareImage: "login-image"
#          revisionID: <integer>
    - name: Mount an NFS share to FS mount in a Category
      category:
        name: "{{ catname }}"
        fsmounts:
           device: "10.245.100.140:/{{ catfs }}"
           mountpoint: "/mnt/{{ catfs }}"
           filesystem: "nfs"
